In [41]:
import torch

vocab = [x for x in " abcdefghijklmnopqrstuvwxyz'?!123456789"]

# Function to convert a list of characters to their corresponding numbers
def char_to_num(chars, char_to_num_mapping):
    char_to_numv = {char: num for num, char in enumerate(vocab)}
    return torch.tensor([char_to_numv[char] for char in chars])

# Function to convert a list of numbers to their corresponding characters
def num_to_char(nums, num_to_char_mapping):
    num_to_charv = {num: char for num, char in enumerate(vocab)}
    return [num_to_charv[num.item()] for num in nums]

# Example usage
nums = torch.tensor([14, 9, 3, 11])
result = num_to_char(nums, vocab)
print(result)

result = char_to_num(['n', 'i', 'c', 'k'], vocab)
print(result)


['n', 'i', 'c', 'k']
tensor([14,  9,  3, 11])


In [ ]:
import torch
import torch.nn as nn

class ConvLSTMModel(nn.Module):
    def __init__(self):
        super(ConvLSTMModel, self).__init__()

        self.conv1 = nn.Conv3d(1, 128, kernel_size=3, padding=1)
        self.relu1 = nn.ReLU()
        self.maxpool1 = nn.MaxPool3d(kernel_size=(1, 2, 2))

        self.conv2 = nn.Conv3d(128, 256, kernel_size=3, padding=1)
        self.relu2 = nn.ReLU()
        self.maxpool2 = nn.MaxPool3d(kernel_size=(1, 2, 2))

        self.conv3 = nn.Conv3d(256, 75, kernel_size=3, padding=1)
        self.relu3 = nn.ReLU()
        self.maxpool3 = nn.MaxPool3d(kernel_size=(1, 2, 2))

        self.flatten = nn.Flatten()

        self.lstm1 = nn.LSTM(input_size=6375, hidden_size=128, bidirectional=True, batch_first=True)
        self.dropout1 = nn.Dropout(0.5)

        self.lstm2 = nn.LSTM(input_size=256, hidden_size=128, bidirectional=True, batch_first=True)
        self.dropout2 = nn.Dropout(0.5)

        self.dense = nn.Linear(256, 41)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = self.maxpool1(self.relu1(self.conv1(x)))
        x = self.maxpool2(self.relu2(self.conv2(x)))
        x = self.maxpool3(self.relu3(self.conv3(x)))
        x = self.flatten(x)

        # Reshape x to have a sequence length of 1 and expand the dimensions
        x = x.view(x.size(0), 1, -1).expand(x.size(0), 75, x.size(1))

        x_lstm1, _ = self.lstm1(x)
        x_lstm1 = self.dropout1(x_lstm1[:, -1, :])

        x_lstm2, _ = self.lstm2(x_lstm1.unsqueeze(1))
        x_lstm2 = self.dropout2(x_lstm2[:, -1, :])

        x_dense = self.dense(x_lstm2)
        x_out = self.softmax(x_dense)

        return x_out

# Instantiate the model
model = ConvLSTMModel()

# Create a random input with the same shape as the Sequential model's input
random_input = torch.randn((1, 75, 46, 140))

# Forward pass to get predictions
predictions = model(random_input)

print(predictions)


In [1]:
import tensorflow as tf
import os
# Path to your TensorFlow checkpoint
checkpoint_path = os.path.join(os.getcwd(), 'models', 'checkpoint')

# Initialize an empty dictionary to store the weights
weights_dict = {}

# Load each variable's value into the dictionary
with tf.compat.v1.Session() as sess:
    for var in tf.train.list_variables(checkpoint_path):
        var_name = var[0]
        var_value = tf.train.load_variable(checkpoint_path, var_name)
        weights_dict[var_name] = var_value

# Example of accessing specific keys from the weights dictionary
# Here, you can access the keys of the weights dictionary and manipulate them as needed
for key in weights_dict:
    print(key, '::', weights_dict[key])

_CHECKPOINTABLE_OBJECT_GRAPH :: b'\n\xc0\x03\n\x18\x08\x01\x12\x14layer_with_weights-0\n\x0b\x08\x01\x12\x07layer-0\n\x0b\x08\x02\x12\x07layer-1\n\x0b\x08\x03\x12\x07layer-2\n\x18\x08\x04\x12\x14layer_with_weights-1\n\x0b\x08\x04\x12\x07layer-3\n\x0b\x08\x05\x12\x07layer-4\n\x0b\x08\x06\x12\x07layer-5\n\x18\x08\x07\x12\x14layer_with_weights-2\n\x0b\x08\x07\x12\x07layer-6\n\x0b\x08\x08\x12\x07layer-7\n\x0b\x08\t\x12\x07layer-8\n\x0b\x08\n\x12\x07layer-9\n\x18\x08\x0b\x12\x14layer_with_weights-3\n\x0c\x08\x0b\x12\x08layer-10\n\x0c\x08\x0c\x12\x08layer-11\n\x18\x08\r\x12\x14layer_with_weights-4\n\x0c\x08\r\x12\x08layer-12\n\x0c\x08\x0e\x12\x08layer-13\n\x18\x08\x0f\x12\x14layer_with_weights-5\n\x0c\x08\x0f\x12\x08layer-14\n\x14\x08\x10\x12\x10predict_function\n\r\x08\x11\x12\toptimizer\n\x15\x08\x12\x12\x11train_tf_function\n\x12\x08\x12\x12\x0etrain_function\n\x06\x12\x04root*\x02\x08\x01\n\x1a\n\n\x08\x13\x12\x06kernel\n\x08\x08\x14\x12\x04bias*\x02\x08\x01\n\x02*\x00\n\x02*\x00\n\x1a\n

In [23]:
a = [-0.01581717,  0.02211865,   -0.01214028, -0.00251676, -0.01251389, -0.00359541, -0.01315751 , 0.00778121 ,-0.00726042 ,-0.01154304 , 0.00131912, -0.00030144, -0.0076811  , 0.00837995 , 0.00896875 ,-0.00404853 , 0.00067654,  0.00173417, -0.00100724 , 0.00417561 , 0.00544827 ,-0.00733909 , 0.00475754, -0.00946006, -0.00266375 ,-0.00145094 ,-0.00377147 ,-0.00688425 , 0.01481302, -0.00585495,  0.00140605 , 0.00548791 ,-0.00347369 ,-0.00641749 , 0.0222531 , -0.00806783, -0.01148799 , 0.01046357 ,-0.00894953 ,-0.00755015 ,-0.01068212,  0.00624578,  0.0019384  ,-0.00186726 ,-0.00961468 ,-0.0154416  ,-0.00605375, -0.01169297, -0.00209417 ,-0.00963513 ,-0.00059942 ,-0.00800047 ,-0.00394584, -0.00025335, -0.01456914 ,-0.00277    , 0.00813367 , 0.00402844 , 0.00137109, -0.00763952, -0.00071181 ,-0.00230226 ,-0.00485248 , 0.00465389 ,-0.01587273, -0.01102389,  0.0107187  ,-0.0096133  ,-0.00160612 , 0.00048553 ,-0.01831518, -0.00407621,  0.00924467 , 0.00790175 ,-0.02059323 , 0.00069766 ,-0.01931619, -0.01270702, -0.0087394  , 0.00322536 ,-0.00783197 ,-0.00043412 ,-0.00683915,  0.00304053, -0.00193796 , 0.01794369 ,-0.01111385 ,-0.00889071 ,-0.01295271,  0.00882019,  0.00125614 ,-0.00423186 ,-0.01581252 ,-0.00180468 ,-0.0117647 , -0.00011554,  0.0021917  , 0.00130104 , 0.00587131 ,-0.00765073 , 0.00323312,  0.0077144 ,  0.00023272 , 0.00196419 , 0.00175337 , 0.01965086 , 0.01587577,  0.00158377, -0.00604943 ,-0.01564396 ,-0.00459792 , 0.0109628  ,-0.0137332 ,  0.00029811, -0.0091716  ,-0.00165499 , 0.01263169 ,-0.00096977 ,-0.00337054,  0.00121156,  0.01053891 ,-0.00281179 , 0.00072034 , 0.00298993 ,-0.0041729 , -0.00970846, -0.01299296, -0.01759243]
print(len(a))


128


In [43]:
import torch

vocab = [x for x in "@abcdefghijklmnopqrstuvwxyz'?!123456789 "]

# Function to convert a list of characters to their corresponding numbers
def char_to_num(chars, char_to_num_mapping):
    char_to_numv = {char: num for num, char in enumerate(vocab)}
    return torch.tensor([char_to_numv[char] for char in chars])

# Function to convert a list of numbers to their corresponding characters
def num_to_char(nums, num_to_char_mapping):
    num_to_charv = {num: char for num, char in enumerate(vocab)}
    return [num_to_charv[num.item()] for num in nums]

# Example usage
nums = torch.tensor([14, 9, 3, 11])
result = num_to_char(nums, vocab)
print(result)

result = char_to_num(['n', 'i', 'c', 'k'], vocab)
print(result)


KeyError: 40

In [4]:
import torch
import torch.nn as nn
from torch.nn import functional as F

import numpy

import string

# Define vocabulary
vocab = list("@abcdefghijklmnopqrstuvwxyz'?!123456789  ")

# Create char_to_num and num_to_char dictionaries
char_to_num = {char: num for num, char in enumerate(vocab)}
num_to_char = {num: char for num, char in enumerate(vocab)}

# Test the conversion
print(f"The vocabulary is: {vocab} (size = {len(vocab)})")

# Example usage
input_string = "hello?"
encoded = [char_to_num[char] for char in input_string]
decoded = ''.join([num_to_char[num] for num in encoded])

print(f"Encoded: {encoded}")
print(f"Decoded: {decoded}")




class MyModel(nn.Module):
    def __init__(self, vocabulary_size):
        super(MyModel, self).__init__()
        self.conv1 = nn.Conv3d(1, 128, kernel_size=3, padding=1)
        self.relu1 = nn.ReLU()
        self.maxpool1 = nn.MaxPool3d(kernel_size=(1, 2, 2))
        self.conv2 = nn.Conv3d(128, 256, kernel_size=3, padding=1)
        self.relu2 = nn.ReLU()
        self.maxpool2 = nn.MaxPool3d(kernel_size=(1, 2, 2))
        self.conv3 = nn.Conv3d(256, 75, kernel_size=3, padding=1)
        self.relu3 = nn.ReLU()
        self.maxpool3 = nn.MaxPool3d(kernel_size=(1, 2, 2))
        self.flatten = nn.Flatten(start_dim=2)
        self.bidirectional_lstm1 = nn.LSTM(6375, 128, bidirectional=True, batch_first=True)
        self.dropout1 = nn.Dropout(0.5)
        self.bidirectional_lstm2 = nn.LSTM(256, 128, bidirectional=True, batch_first=True)
        self.dropout2 = nn.Dropout(0.5)
        self.dense = nn.Linear(256, vocabulary_size)

    def forward(self, x):
        print(x.shape)
        x = self.conv1(x)
        print(x.shape)
        x = self.relu1(x)
        print(x.shape)
        x = self.maxpool1(x)
        print(x.shape)
        x = self.conv2(x)
        print(x.shape)
        x = self.relu2(x)
        print(x.shape)
        x = self.maxpool2(x)
        print(x.shape)
        x = self.conv3(x)
        print(x.shape)
        x = self.relu3(x)
        print(x.shape)
        x = self.maxpool3(x)
        print(x.shape)
        x = x.permute(0, 2, 3, 4, 1)
        print(x.shape)
        x = self.flatten(x)
        print(x.shape)
        x, _ = self.bidirectional_lstm1(x)
        print(x.shape)
        x = self.dropout1(x)
        print(x.shape)
        x, _ = self.bidirectional_lstm2(x)
        print(x.shape)
        x = self.dropout2(x)
        print(x.shape)
        x = F.softmax(self.dense(x), dim = 1)
        print(x.shape)
        return x

frames = 75
rows = 46
columns = 140
channels = 1
random_input = torch.randn(1, channels, frames, rows, columns)
model = MyModel(41)
model.load_state_dict(torch.load('model.pth'))
output = model(random_input)
output = torch.squeeze(output).argmax(dim = 1)

The vocabulary is: ['@', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', "'", '?', '!', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ', ' '] (size = 41)
Encoded: [8, 5, 12, 12, 15, 28]
Decoded: hello?
torch.Size([1, 1, 75, 46, 140])
torch.Size([1, 128, 75, 46, 140])
torch.Size([1, 128, 75, 46, 140])
torch.Size([1, 128, 75, 23, 70])
torch.Size([1, 256, 75, 23, 70])
torch.Size([1, 256, 75, 23, 70])
torch.Size([1, 256, 75, 11, 35])
torch.Size([1, 75, 75, 11, 35])
torch.Size([1, 75, 75, 11, 35])
torch.Size([1, 75, 75, 5, 17])
torch.Size([1, 75, 5, 17, 75])
torch.Size([1, 75, 6375])
torch.Size([1, 75, 256])
torch.Size([1, 75, 256])
torch.Size([1, 75, 256])
torch.Size([1, 75, 256])
torch.Size([1, 75, 41])


In [6]:
frames = 75
rows = 46
columns = 140
channels = 1

random_input = torch.randn(1, channels, frames, rows, columns)
model = MyModel(41)
# print(model)
output = model(random_input)
# print("Output shape:", output.shape)
output = torch.squeeze(output).argmax(dim = 1).tolist()
# print(output)
s = ""
for i in output:
    s += num_to_char[i]
print(s)

torch.Size([1, 1, 75, 46, 140])
torch.Size([1, 128, 75, 46, 140])
torch.Size([1, 128, 75, 46, 140])
torch.Size([1, 128, 75, 23, 70])
torch.Size([1, 256, 75, 23, 70])
torch.Size([1, 256, 75, 23, 70])
torch.Size([1, 256, 75, 11, 35])
torch.Size([1, 75, 75, 11, 35])
torch.Size([1, 75, 75, 11, 35])
torch.Size([1, 75, 75, 5, 17])
torch.Size([1, 75, 5, 17, 75])
torch.Size([1, 75, 6375])
torch.Size([1, 75, 256])
torch.Size([1, 75, 256])
torch.Size([1, 75, 256])
torch.Size([1, 75, 256])
torch.Size([1, 75, 41])
    slewsy1bq?3tz4q2bsa6u78ujer1c'gpop6lfhgvdcamy8y xmwoxlqk4h@6!3ek!g4s'ki


In [9]:
import torch
a = torch.randn(3, 4, 5)
print(a)
a = a.permute(1, 2, 0)
print(a)

tensor([[[-0.9944,  1.0100, -0.4697,  0.1032, -0.7640],
         [-1.0932, -0.8107,  1.2131,  1.7615, -0.7259],
         [-1.7364, -1.5550, -0.8940,  0.3361,  0.8635],
         [ 0.9084, -0.6853,  1.0468, -0.2145, -1.2931]],

        [[-1.1779, -0.0323, -0.1473,  1.1643,  1.7116],
         [-0.0353, -0.7758, -0.8153,  1.9162,  0.0365],
         [ 0.3010, -0.5619,  1.1747, -0.6238, -0.6209],
         [-1.5794,  0.0653,  1.1817, -0.1344,  0.6898]],

        [[ 1.9288,  0.4088,  0.2621, -0.2921, -0.0048],
         [-1.0607, -1.5211, -0.7718, -1.7526,  0.1018],
         [-1.2403,  0.1934,  2.0048, -0.6988,  0.0953],
         [ 0.1291, -0.7261,  1.1802, -0.9640, -1.8664]]])
tensor([[[-0.9944, -1.1779,  1.9288],
         [ 1.0100, -0.0323,  0.4088],
         [-0.4697, -0.1473,  0.2621],
         [ 0.1032,  1.1643, -0.2921],
         [-0.7640,  1.7116, -0.0048]],

        [[-1.0932, -0.0353, -1.0607],
         [-0.8107, -0.7758, -1.5211],
         [ 1.2131, -0.8153, -0.7718],
         [ 1.761

In [88]:
# Access the weight matrix for a specific layer and print its shape
w = []
w.append(model.conv1.weight)
w.append(model.conv2.weight)
w.append(model.conv3.weight)
# w.append(model.bidirectional_lstm1.weight)
# w.append(model.bidirectional_lstm2.weight)

for i in w:
    print(i.shape)

# with torch.no_grad():
#     model.fc1.weight.copy_(weight_matrix_fc1)
#     model.fc2.weight.copy_(weight_matrix_fc2)

torch.Size([128, 1, 3, 3, 3])
torch.Size([256, 128, 3, 3, 3])
torch.Size([75, 256, 3, 3, 3])


In [89]:
for name, param in model.named_parameters():
    print(name, param.shape)

conv1.weight torch.Size([128, 1, 3, 3, 3])
conv1.bias torch.Size([128])
conv2.weight torch.Size([256, 128, 3, 3, 3])
conv2.bias torch.Size([256])
conv3.weight torch.Size([75, 256, 3, 3, 3])
conv3.bias torch.Size([75])
bidirectional_lstm1.weight_ih_l0 torch.Size([512, 6375])
bidirectional_lstm1.weight_hh_l0 torch.Size([512, 128])
bidirectional_lstm1.bias_ih_l0 torch.Size([512])
bidirectional_lstm1.bias_hh_l0 torch.Size([512])
bidirectional_lstm1.weight_ih_l0_reverse torch.Size([512, 6375])
bidirectional_lstm1.weight_hh_l0_reverse torch.Size([512, 128])
bidirectional_lstm1.bias_ih_l0_reverse torch.Size([512])
bidirectional_lstm1.bias_hh_l0_reverse torch.Size([512])
bidirectional_lstm2.weight_ih_l0 torch.Size([512, 256])
bidirectional_lstm2.weight_hh_l0 torch.Size([512, 128])
bidirectional_lstm2.bias_ih_l0 torch.Size([512])
bidirectional_lstm2.bias_hh_l0 torch.Size([512])
bidirectional_lstm2.weight_ih_l0_reverse torch.Size([512, 256])
bidirectional_lstm2.weight_hh_l0_reverse torch.Size([5

In [92]:
model.dense.weight.data = torch.rand(41, 256)
print(model.dense.weight.data)

tensor([[0.9312, 0.0282, 0.0572,  ..., 0.6491, 0.3524, 0.4563],
        [0.0959, 0.3324, 0.8985,  ..., 0.2482, 0.0224, 0.5879],
        [0.7973, 0.9018, 0.6852,  ..., 0.1390, 0.7458, 0.7485],
        ...,
        [0.9573, 0.7661, 0.0853,  ..., 0.6452, 0.8902, 0.5438],
        [0.4745, 0.0318, 0.5804,  ..., 0.1880, 0.8874, 0.0462],
        [0.4817, 0.7049, 0.3176,  ..., 0.8954, 0.1360, 0.6941]])


In [49]:
import torch

# Create a tensor with shape (3, 2, 5)
original_tensor = torch.randn(3, 2)

# Transpose the tensor to shape (2, 3, 5)
transposed_tensor = original_tensor.permute(1, 0)

# Print the original and transposed tensors
print("Original Tensor:\n", original_tensor)
print("\nTransposed Tensor:\n", transposed_tensor)


Original Tensor:
 tensor([[ 0.0069, -0.7240],
        [-0.4757, -0.6105],
        [ 0.8939, -0.8675]])

Transposed Tensor:
 tensor([[ 0.0069, -0.4757,  0.8939],
        [-0.7240, -0.6105, -0.8675]])


In [34]:
import torch
import torch.nn as nn

class SimpleConv3DNet(nn.Module):
    def __init__(self):
        super(SimpleConv3DNet, self).__init__()
        self.conv1 = nn.Conv3d(1, 16, kernel_size=3, padding=1)
        self.conv2 = nn.Conv3d(16, 32, kernel_size=3, padding=1)
        self.pool = nn.MaxPool3d(kernel_size=2, stride=2)
        self.fc1 = nn.Linear(32 * 4 * 4 * 4, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool(torch.relu(self.conv2(x)))
        x = x.view(-1, 32 * 4 * 4 * 4)  # Flatten for the fully connected layer
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Create an instance of the network
net = SimpleConv3DNet()
# print(net)
# Example input
input_data = torch.randn(10, 1, 32, 32, 32)  # Batch size of 10, 1 channel, and 32x32x32 volume

# Forward pass
output = net(input_data)

# Print the output
print(output)

# Print the network architecture


tensor([[ 4.4600e-02, -8.8568e-02,  1.6360e-01, -1.3329e-02, -6.5836e-02,
          4.9593e-03,  1.6162e-01, -1.3007e-01,  2.7315e-01,  1.7466e-01],
        [ 8.6779e-03,  1.2066e-02,  2.0841e-01, -3.4308e-02, -1.2934e-01,
         -5.2720e-02,  7.8861e-02, -6.9394e-02,  2.1545e-01,  1.4339e-01],
        [-1.0326e-01, -2.0896e-01,  4.3580e-01,  2.2304e-01, -1.9655e-01,
          9.3994e-02,  7.8267e-02, -1.4781e-01,  3.0250e-02, -5.9381e-02],
        [-5.5331e-02, -2.2304e-02,  2.1145e-01,  9.3849e-02, -1.0626e-02,
          1.0496e-01, -1.3197e-03, -8.4057e-02,  4.9393e-02,  7.0372e-03],
        [ 3.9546e-02, -1.0445e-01,  1.4751e-01,  8.5721e-02, -1.7697e-02,
          1.2041e-01,  1.6641e-01, -1.8621e-01,  1.6297e-01,  1.5133e-01],
        [ 5.9413e-02, -6.6116e-02,  2.1735e-01, -8.5872e-03, -1.7942e-01,
         -4.7167e-02,  1.5560e-01, -1.8424e-01,  3.1978e-01,  1.3211e-01],
        [ 2.5659e-03, -5.9468e-02, -5.5330e-03,  3.4490e-02,  2.2970e-02,
         -3.6296e-02,  1.7164e-0

In [5]:
import tensorflow as tf
import numpy as np

# Generate a random 3D array (representing 2 time steps of a 3x3 matrix)
random_data = np.random.randn(2, 3, 3)
print(random_data)

# Reshape the data to add a batch size dimension
random_data = np.expand_dims(random_data, axis=0)
print(random_data.shape)
# Define a model with TimeDistributed and Flatten
model = tf.keras.Sequential([
    tf.keras.layers.TimeDistributed(tf.keras.layers.Flatten(), input_shape=(None, 3, 3))
])

# Apply the model to the data
output = model.predict(random_data)

# Print the result
print(output)
print(output.shape)

[[[-0.41526872  0.23916782  0.78071902]
  [ 0.67880267  0.85501525 -0.76401702]
  [ 0.95931368 -0.22128913  1.47956511]]

 [[-2.36044543  0.86352346 -0.03936559]
  [-0.1677009   1.469808   -0.73807701]
  [-0.19190858 -0.60359761  0.58278017]]]
(1, 2, 3, 3)
1/1 [==============================] - 0s 33ms/step
[[[-0.41526872  0.23916782  0.78071904  0.67880267  0.8550153
   -0.76401705  0.9593137  -0.22128913  1.4795651 ]
  [-2.3604455   0.8635235  -0.03936559 -0.1677009   1.469808
   -0.738077   -0.19190858 -0.6035976   0.5827802 ]]]
(1, 2, 9)


In [21]:
import numpy as np
np.set_printoptions(threshold=np.inf)
a = np.random.rand(10, 75, 46, 140, 1)
with open("datatemp.bin", "wb") as file:
    a.tofile(file)


In [22]:
print(a[0][74][40][7][0])

0.9958083295418253
